export default[
    {
        path:"/center",
        component:()=>import("@/pages/Center"),
        meta:{showFooter:true},
        children:[
            {
                path:"myorder",
                component:()=>import("@/pages/Center/myOrder"),
            },
            {
                path:"groupOrder",
                component:()=>import("@/pages/Center/groupOrder"),
            },
            {
                path:"/center",
                redirect:"/center/myorder"
            }
        ]
    },
    {
        path:"/paysuccess",
        component:()=>import("@/pages/PaySuccess"),
        meta:{showFooter:true},
        beforeEnter: (to, from, next) => {
            if(from.path=="/pay"||from.path=="/") next()
            else{
                next(false)
            }
        }
    },
    {
        path:"/pay",
        component:()=>import("@/pages/Pay"),
        meta:{showFooter:true},
        beforeEnter: (to, from, next) => {
            if(from.path=="/trade"||from.path=="/") next()
            else{
                next(false)
            }
        }
    },
    {
        path:"/home",
        component:()=>import("@/pages/Home"),
        meta:{showFooter:true}
    },
    {
        path:"/search/:keyword?",
        component:()=>import("@/pages/Search"),
        meta:{showFooter:true},
        name:"search"
    },
    {
        path:"/login",
        component:()=>import("@/pages/Login"),
        meta:{showFooter:false}
    },
    {
        path:"/register",
        component:()=>import("@/pages/Register"),
        meta:{showFooter:false}
    },
    {
        path:"/detail/:skuid",
        component:()=>import("@/pages/Detail"),
        meta:{showFooter:true}
    },
    {
        path:"/addcartsuccess",
        name:"addcartsuccess",
        component:()=>import("@/pages/AddCartSuccess"),
        meta:{showFooter:true}
    },
    {
        path:"/shopcart",
        component:()=>import("@/pages/ShopCart"),
        meta:{showFooter:true}
    },
    {
        path:"/trade",
        component:()=>import("@/pages/Trade"),
        meta:{showFooter:true},
        beforeEnter: (to, from, next) => {
            if(from.path=="/shopcart"||from.path=="/") next()
            else{
                next(false)
            }
        }
    },
    //重定向，在项目跑起来时，访问/，立马让他定向到首页
    {
        path:"*",
        redirect:"/home"
    }
]